### ISSUE TITLE
Want to automatically load additional subtitle files.

### ISSUE THREAD

**Issue by Insua** [jarnedemeulemeester/findroid#922] opened 2024-12-30 03:24 UTC
Since I've already uploaded additional subtitle files to Jellyfin, it's obvious that I want to use these subtitles instead of the ones embedded in the MKV file. Therefore, it's only natural for the player to automatically load the additional subtitle files, but currently, I still need to manually select them every time.

**Comment by jarnedemeulemeester** [comment] 2024-12-31 18:24
Duplicate of #722

**Closed by jarnedemeulemeester** 2024-12-31 18:24 UTC
Labels: enhancement
