### ISSUE TITLE
Library scroll position is not remembered

### ISSUE THREAD

**Issue by AnonymousWebHacker** [jarnedemeulemeester/findroid#201] opened 2022-11-22 06:28 UTC
**Describe the bug**
It happens very often.

For example, I am looking at the movie catalogue, and when I enter a movie, to read its synopsis, once, I press the android return button (the list is restarted by going back to the beginning of the movie list). You have to scroll down again, to continue where you found the movie

**To Reproduce**
1.  Scroll down in the list of movies and select a movie to read its synopsis
2. Click on the system return button (back)

Findroid sends me to the beginning of the list, and does not stay until where I had scolled

**Expected behavior**
No more having to scroll the entire list, to return to where I left off

**Device info (please complete the following information):**
 - Device: Redmi 9A
 - Android version: 11
 - App version: all

**Comment by jarnedemeulemeester** [comment] 2022-11-22 15:53
Hmm I cannot reproduce this.
When I scroll down the list, select a movie and go back, the list is still at the location where I left off.

How much memory (RAM) does your device have? Maybe it's a memory issue but I'm not sure.
I will also do some more testing.

**Comment by AnonymousWebHacker** [comment] 2022-11-22 23:54
Redmi 9A
Android: 11 MIUI Chinese
RAM: 2.5 GB

https://user-images.githubusercontent.com/43164089/203444328-2bb3676c-e31f-4df8-b653-ee8bb21a7757.mp4

**Comment by MudssirAhmed** [comment] 2023-02-01 03:41
Hey @jarnedemeulemeester I want to fix this issue, Can you assign it to me if possible.

**Comment by MudssirAhmed** [comment] 2023-02-01 14:33
I'm also facing trouble when I'm going to recreate this issue.

**Comment by AnonymousWebHacker** [comment] 2023-02-01 20:44
I can recreate it both in low-resource devices such as 2gb of ram, and in others with 8 Gb of RAM, so I think it's a general error.

**Comment by MudssirAhmed** [comment] 2023-02-02 03:37
> I can recreate it both in low-resource devices such as 2gb of ram, and in others with 8 Gb of RAM, so I think it's a general error.

Okay let me check once again in low memory devices.

**Comment by jarnedemeulemeester** [comment] 2023-02-02 08:05
Yeah I'm still not able to reproduce it, in low-resource devices or with devices with more resources. This may be a device specific issue for some reason. 
This may also be solved when we migrate to compose in the future.

**Comment by MudssirAhmed** [comment] 2023-02-02 15:34
Ya so we can leave it for now until we add compose.

**Closed** 2023-02-11 09:41 UTC
Labels: bug
