### ISSUE TITLE
External ASS subtitles cannot be selected when using mpv player

### ISSUE THREAD

**Issue by CodeName393** [jarnedemeulemeester/findroid#160] opened 2022-09-02 05:37 UTC
**Describe the bug**
Some subtitles are in the ass format.
The exo player brings up external as subtitles, but the mpv player cannot bring up external as subtitles.

**Device info (please complete the following information):**
 - Device: Galaxy Fold3
 - Android version: 12(Level 31)
 - App version: 0.6.1

**Comment by jarnedemeulemeester** [comment] 2022-09-02 17:01
Confirmed external ASS/SSA subtitles are indeed missing. (Same for VTT)
They worked while I was developing but I changed something which broke them.
Fixing it now...

**Comment by ACViper** [comment] 2022-09-29 00:34
Is this still being worked on? External subs/audio doesn't work rn. Loving the app so far, this is my only complaint with it.

**Comment by jarnedemeulemeester** [comment] 2022-10-27 11:28
An update on this:
I fixed this on a local build. 
I haven't pushed a new libmpv binary because I wanted to include a fix for VTT subs as well, but I have not been able to get those working.

But rest assured, the next release (0.7.0) will include the fix for external ASS subtitles. :smiley: 
I cannot say when 0.7.0 will be released as there are still a lot of things I want to include in that update.

**Closed** 2022-11-04 22:56 UTC
Labels: bug
