### ISSUE TITLE
[Feature request] Intro skipping

### ISSUE THREAD

**Issue by JakeDevs** [jarnedemeulemeester/findroid#244] opened 2023-01-26 12:59 UTC
There is a plugin for this but I'm not sure how easy it will be to implement it but it is a very useful feature. Skipping through the into every single episode gets very annoying.

**Comment by jarnedemeulemeester** [comment] 2023-01-26 14:52
Intro skipping has been implemented in v0.9.0. Should be available on the Google Play Store in the coming days.

Duplicate of #163

**Closed by jarnedemeulemeester** 2023-01-26 14:52 UTC
Labels: bug
