### ISSUE TITLE
Add a way to customize mpv's config and input files. 

### ISSUE THREAD

**Issue by Estebiu** [jarnedemeulemeester/findroid#857] opened 2024-10-08 14:41 UTC
**Describe the solution you'd like**
A way to let you set custom values in mpv (custom keybinds, custom preferences)

**Describe alternatives you've considered**
Letting you open directly mpv-android instead of the built-in libmpv implementation?

**Comment by jarnedemeulemeester** [comment] 2024-10-12 13:25
Duplicate of #157

**Closed by jarnedemeulemeester** 2024-10-12 13:25 UTC
Labels: enhancement
