### ISSUE TITLE
Pause on next track

### ISSUE THREAD

**Issue by enter-a-random-username** [jarnedemeulemeester/findroid#845] opened 2024-09-27 10:58 UTC
**Describe the bug**
Since last release (0.15.2) next tracks starts pause and power saving is disabled. No system update or something released was done. Maybe that issue is part of MPV

**To Reproduce**
1.Watch a episode
2. Next episode is paused (fast forwards sometimes changes the behavior)

**Expected behavior**
Run the next episode

**Device info (please complete the following information):**
 - Device:  Multiple devices
 - Android version: Multiple versions
 - App version:  0.15.2 (28)
 - Jellyfin version: master (all other players are working)
 -

**Comment by jarnedemeulemeester** [comment] 2024-10-12 13:29
Duplicate of #837

**Closed by jarnedemeulemeester** 2024-10-12 13:29 UTC
Labels: bug
