### ISSUE TITLE
[Suggestion] Search button in main UI and live searches.

### ISSUE THREAD

**Issue by fmchris10** [jarnedemeulemeester/findroid#214] opened 2022-12-05 17:21 UTC
A search button in the main UI would be a nice touch, instead of needing to go into the media tab.

Also, can the searches instantly respond to what is written? Showing the nearest results below.

**Comment by BluePixel4k** [comment] 2022-12-10 23:58
Duplicate of #84 and #95

**Comment by jarnedemeulemeester** [comment] 2022-12-11 00:02
Search button has been added to the home screen
This is a duplicate of #84 

The live searches / suggestions is a duplicate of #95. Let's discuss it there

**Closed by jarnedemeulemeester** 2022-12-11 00:02 UTC
Labels: enhancement
