### ISSUE TITLE
Socket timed out,please add more timeout for remote playback

### ISSUE THREAD

**Issue by msycn** [jarnedemeulemeester/findroid#190] opened 2022-11-04 00:29 UTC
Describe the bug
Unable to play ,Socket timed out
but can be playback on local

To Reproduce

1. Create .txt file 
2. edit .txt file to type video link such as (https://www.youtube/d/.....1080p.h265.mkv) 
3. change .txt to .strm
4. refresh scan your library 
5.Go to 'Movie'
6.Click on 'play'
7.See error

**Expected behavior**
increase socket_timeout=10000] ms
 to socket_timeout=20000] ms
thank you

**Screenshots**
![photo_2022-11-03_20-28-47](https://user-images.githubusercontent.com/85003651/199859795-7d83ac61-79c7-49cc-b42e-b5f56fcffcd0.jpg)

**Device info (please complete the following information):**
 - Device: [Xiaomi 12S Ultra]
 - Android version: [12]
 - App version: [v0.6.1]
 - Jellyfin version: [10.8.7]

**Additional context**
Socket timed out
 sa.g: Socket timed out
 at ra.e.l(SourceFile:4)
 at ra.e$d.j(Unknown Source:17)
 at v8.a.k(Unknown Source:8)
 at e8.j.d(SourceFile:5)
 at e8.j$a.k(SourceFile:3)
 at v8.a.k(Unknown Source:31)
 at e8.j.d(SourceFile:5)
 at e8.j$a.k(SourceFile:3)
 at v8.a.k(Unknown Source:31)
 at e8.j.d(SourceFile:5)
 at e8.j$a.k(SourceFile:3)
 at v8.a.k(Unknown Source:31)
 at e8.j.d(SourceFile:5)
 at e8.j$a.k(SourceFile:3)
 at v8.a.k(Unknown Source:31)
 at k9.q0.run(Unknown Source:86)
 at p9.e.run(Unknown Source:12)
 at q9.l.run(Unknown Source:2)
 at q9.a$a.run(SourceFile:9)
Caused by: x7.b: Socket timeout has expired [url=https://vip.naifeis.com/Items/906e184b-b401-0e60-f504-b99d95aec743/PlaybackInfo, socket_timeout=10000] ms
 at io.ktor.client.features.HttpTimeoutKt.SocketTimeoutException(SourceFile:2)
 at io.ktor.client.engine.okhttp.OkUtilsKt.mapOkHttpException(Unknown Source:22)
 at io.ktor.client.engine.okhttp.OkUtilsKt.access$mapOkHttpException(Unknown Source:0)
 at p7.a.a(Unknown Source:18)
 at fa.e$a.run(SourceFile:13)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:920)
Caused by: java.net.SocketTimeoutException: timeout
 at ia.q$c.m(SourceFile:1)
 at ia.o.g(SourceFile:1)
 at fa.c.d(Unknown Source:2)
 at ga.b.a(SourceFile:29)
 at ga.g.b(SourceFile:7)
 at fa.a.a(SourceFile:16)
 at ga.g.b(SourceFile:7)
 at da.a.a(SourceFile:29)
 at ga.g.b(SourceFile:7)
 at ga.a.a(SourceFile:21)
 at ga.g.b(SourceFile:7)
 at ga.i.a(SourceFile:26)
 at ga.g.b(SourceFile:7)
 at fa.e.f(SourceFile:10)
 at fa.e$a.run(SourceFile:8)
 ... 3 more

**Comment by jarnedemeulemeester** [comment] 2022-11-05 09:22
This is a duplicate of #175 
Let's continue the discussion there.

**Closed by jarnedemeulemeester** 2022-11-05 09:22 UTC
Labels: bug, duplicate
