### ISSUE TITLE
Skip intro button is tied to the media controls

### ISSUE THREAD

**Issue by UriSheinman** [jarnedemeulemeester/findroid#833] opened 2024-09-12 15:47 UTC
**Describe the bug**
The skip intro button appears and disappears as part if the media controls are showing or not, though they should be separate.
**To Reproduce**
1. Watch a content with skip intro
2. Tap screen to show media control
3. Tap again to make the media control go away
4. The skip intro button disappears with the media controls

**Expected behavior**
The skip intro button should behave independently and not part of the media controls

**Screenshots**

https://github.com/user-attachments/assets/f8d2ddc3-51eb-4c02-ba03-85b1abc18995

**Device info (please complete the following information):**
 - Device: nothing phone 1
 - Android version: 14
 - App version: 0.15.2
 - Jellyfin version: 10.9.9

**Comment by jarnedemeulemeester** [comment] 2024-09-24 20:51
This is actually the intended behavior for now. However we should maybe add some options to change the behavior.

Closing this as it's intended for now.

**Closed** 2024-09-24 20:51 UTC
Labels: bug
