### ISSUE TITLE
[Feature Request] Support for MKV chapters

### ISSUE THREAD

**Issue by Margit420** [jarnedemeulemeester/findroid#437] opened 2023-07-10 23:23 UTC
Ideas for implementation (highly recommend 3 & 4)

1) A menu like VLC. (not recommended)

2) Tap the title for a a drop-down menu.

3) New previous/next buttons next to the "lock" button.

4) Seek bar gets split into chapters with the chapter title above + haptic feedback and magnetic pull to the start of each chapter. (Kinda like YouTube)

5) Setting toggle to navigate chapters with the previous/next episode buttons + long press to navigate episodes.

6) Simple circles on the seek bar to indicate chapters like (MPC)

**Comment by Natanel-Shitrit** [comment] 2023-08-12 11:25
Duplicate of #158

Please do not open a new issue if there is an existing one with the same issue / request 😄
You can always add a comment with your additions if you have something you want to add to the original request!

**Closed** 2023-08-14 16:05 UTC
