### ISSUE TITLE
Not showing extras

### ISSUE THREAD

**Issue by smarttommyau** [jarnedemeulemeester/findroid#391] opened 2023-05-31 12:53 UTC
**Describe the bug**
Videos in extra not being showned

**To Reproduce**
1. Have some extra video
2. Cannot show

**Expected behavior**
It should as how the web client does

**Screenshots**

**Device info (please complete the following information):**
 - Device: [e.g. Google Pixel 3]
 - Android version: [e.g. 12]
 - App version: [e.g. v0.1.1 (2)]
 - Jellyfin version: [e.g. 10.8.5]

**Additional context**

**Comment by Natanel-Shitrit** [comment] 2023-07-11 20:46
This is not a bug, extras are not supported yet 😄
This is tracked in #292, please close this issue so we can keep track of it in one place!

**Closed** 2023-07-11 23:27 UTC
Labels: bug
